export { Home } from "./home/index";
export { Stocks } from "./stocks/index";
export { Login } from "./login/index";
export { Account } from "./account/index";
export { Dashboard } from "./dashboard/index";
export { Error } from "./error/index";
export { Register } from "./register/index";
export { Watchlist } from "./watchlist/index";
export { Stock } from "./stock/index";
